const express =require("express")
const mongoose=require("mongoose")
const dotenv=require("dotenv").config()
const cors=require("cors")
const authController = require("./controllers/authController")
const PropertyController = require("./controllers/propertyController")
const uploadController = require("./controllers/uploadController")
const yachtController = require("./controllers/yachtController")
const commentController = require("./controllers/commentController")
const userController = require("./controllers/userController")
const app=express()

mongoose.set("strictQuery",false)
mongoose.connect(process.env.MONGO_URL,()=>console.log("MongoDb Connected Succefully"))
app.use('/images',express.static('public/images'))
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use("/auth",authController)
app.use("/property",PropertyController)
app.use("/upload",uploadController)
app.use("/yacht",yachtController)
app.use("/comment",commentController)
app.use("/user",userController)


app.listen(process.env.PORT,()=>console.log("Server Connected"))
